Modify API output format;Modify test cases

diff --git a/test/integration/functionality/100_validate b/test/integration/functionality/100_validate
--- a/test/integration/functionality/100_validate
+++ b/test/integration/functionality/100_validate
@@ -1,17 +1,19 @@
 #!/bin/bash
 function _seal()
 {
-    local datapath_l=$1
-    local storepath_l=$2
-    local curtmp=$TMPFILE.$(date +%N)${RANDOM}
-    seal $datapath_l &>$curtmp
+    local filesize=$((RANDOM % 17 + 1))m
+    $GEN_RANDOM_DATA ${filesize} $datadir/$filesize
     if [ $? -ne 0 ]; then
-        verbose ERROR "Seal file failed!" n
-        rm $curtmp
+        verbose ERROR "generate random data failed!"
         exit 1
     fi
-    cat -v $curtmp 2>/dev/null
-    rm $curtmp
+    local cid_l=$(seal $datadir/$filesize)
+    rm $datadir/$filesize
+    if [ ${#cid_l} -ne 46 ]; then
+        verbose ERROR "seal file failed!"
+        exit 1
+    fi
+    echo $cid_l
 }
 
 function _validate()
@@ -26,6 +28,11 @@ function _validate()
 function validate_exit()
 {
     rm -rf $tmpdir
+
+    # Delete test files
+    for cid in ${cid_arry[@]}; do
+        delete_file $cid &>/dev/null
+    done
 }
 
 
@@ -54,7 +61,6 @@ srd_num=$(get_config ".functionality|.validate|.srd_num")
 deleted_srd=$(get_config ".functionality|.validate|.deleted_srd")
 file_num=$(get_config ".functionality|.validate|.file_num")
 deleted_file=$(get_config ".functionality|.validate|.deleted_file")
-data_arry=($(ls $datadir))
 
 ### Srd some space
 srd_real $srd_num &>/dev/null
@@ -69,24 +75,20 @@ for sf in $(ls $srd_path); do
 done
 
 ### Seal some file
-data_arry_size=${#data_arry[@]}
+cid_arry=()
+cid_idx=0
 i=0
-while [ $i -lt $file_num ]; do
-    index=$((RANDOM % data_arry_size))
-    file=${data_arry[$index]}
-    if [[ $file =~ 128 ]] || [[ $file =~ 256 ]] || [[ $file =~ 512m ]] || [[ $file =~ 1024 ]] ; then
-        continue
-    fi
-    cid=$(_seal $datadir/$file $testfiledir)
-    ((i++))
+while [ $((i++)) -lt $file_num ]; do
+    _seal &>$TMPFILE
+    cid_arry[$((cid_idx++))]=$(cat $TMPFILE)
 done
 # Delete some file
 i=0
-while [ $((i++)) -lt $deleted_file ]; do
-    for file in $(ls $testfiledir); do
-        rm -rf $testfiledir/$file
+for cid in ${cid_arry[@]}; do
+    if [ $((i++)) -ge $deleted_file ]; then
         break
-    done
+    fi
+    delete_file_block_random $cid
 done
 
 ### Validate
@@ -111,12 +113,6 @@ real_vfile=$(cat $TMPFILE | jq '.files|.valid|.num')
 expected_vfile=$((file_num-deleted_file))
 if [ $real_vfile -ne $expected_vfile ]; then
     verbose ERROR "expected valid file num:$expected_vfile, real:$real_vfile" n
-    ret=1
-fi
-real_lfile=$(cat $TMPFILE | jq '.files|.lost|.num')
-expected_lfile=$deleted_file
-if [ $real_lfile -ne $expected_lfile ]; then
-    verbose ERROR "expected lost file num:$expected_lfile, real:$real_lfile" n
     ret=1
 fi
 
diff --git a/test/integration/functionality/200_seal b/test/integration/functionality/200_seal
--- a/test/integration/functionality/200_seal
+++ b/test/integration/functionality/200_seal
@@ -1,22 +1,23 @@
 #!/bin/bash
 function _seal()
 {
-    local datapath_l=$1
-    local storepath_l=$2
-    local curtmp=$TMPFILE.$(date +%N)${RANDOM}
-    seal_file $datapath_l $storepath_l &>$curtmp
+    local filesize=$((RANDOM % 17 + 1))m
+    local filename=${filesize}.$(date +%N)${RANDOM}
+    $GEN_RANDOM_DATA ${filesize} $datadir/$filename
     if [ $? -ne 0 ]; then
-        verbose ERROR "Seal file failed!" n
-        rm $curtmp
+        verbose ERROR "generate random data failed!"
         exit 1
     fi
-    local sealed_hash=$(cat -v $curtmp | jq '.path' | sed 's/"//g' | xargs -I {} basename {} 2>/dev/null)
-    sealed_hash=${sealed_hash:0:64}
+    local cid_l=$(seal $datadir/$filename)
+    rm $datadir/$filename
+    if [ ${#cid_l} -ne 46 ]; then
+        verbose ERROR "seal file failed!"
+        exit 1
+    fi
     (
       flock -w 30 200
-      echo $sealed_hash >> $syncfile
+      echo $cid_l >> $syncfile
     ) 200>$LOCKFILE
-    rm $curtmp
 }
 
 function _store_meta()
@@ -27,6 +28,11 @@ function _store_meta()
 
 function seal_exit()
 {
+    # Delete test files
+    for cid in $(cat $syncfile); do
+        delete_file $cid &>/dev/null
+    done
+
     rm -rf $tmpdir
 }
 
@@ -50,24 +56,25 @@ trap 'seal_exit' EXIT
 . $scriptdir/utils.sh
 
 
-data_arry=($(ls $datadir))
-data_size=${#data_arry[@]}
 timeout=300
 
 true > $syncfile
-# Seal some file
-for file in ${data_arry[@]}; do
-    _seal $datadir/$file $testfiledir &
+### Seal some file
+data_size=10
+i=0
+while [ $((i++)) -lt $data_size ]; do
+    _seal &
 done
-
-while [ $(cat $syncfile | wc -l) -ne ${data_size} ] && [ $timeout -gt 0 ]; do
+# Wait seal task finish
+while [ $(cat $syncfile | wc -l) -lt ${data_size} ] && [ $timeout -gt 0 ]; do
     sleep 1
     ((timeout--))
 done
 
-_store_meta &>/dev/null
-for hash in $(cat $syncfile); do
-    if ! check_hash "$hash" "unconfirmed"; then
+### Check seal result
+get_file_info_all &>$TMPFILE
+for cid in $(cat $syncfile); do
+    if ! grep $cid $TMPFILE &>/dev/null; then
         verbose ERROR "Seal file failed!Cannot find sealed hash." n
         exit 1
     fi
diff --git a/test/integration/functionality/501_boundary b/test/integration/functionality/501_boundary
--- a/test/integration/functionality/501_boundary
+++ b/test/integration/functionality/501_boundary
@@ -1,19 +1,17 @@
 #!/bin/bash
 function _seal()
 {
-    local datapath_l=$1
-    local storepath_l=$2
-    local curtmp=$TMPFILE.$(date +%N)${RANDOM}
-    seal_file $datapath_l $storepath_l &>$curtmp
+    local filesize=$((RANDOM % 17 + 1))m
+    $GEN_RANDOM_DATA ${filesize} $datadir/$filesize
     if [ $? -ne 0 ]; then
-        rm $curtmp
+        verbose ERROR "generate random data failed!"
         return 1
     fi
-    if ! cat $curtmp | jq '.' &>/dev/null; then
-        rm $curtmp
+    local cid_l=$(seal $datadir/$filesize)
+    rm $datadir/$filesize
+    if [ ${#cid_l} -ne 46 ]; then
         return 1
     fi
-    rm $curtmp
 }
 
 function _srd()
@@ -33,6 +31,7 @@ function _srd()
     # Srd task
     local tmp_num=0
     local cur_turn=0
+    verbose INFO "srd num:$srd_num"
     srd_disk_change "$paths" "add" &>/dev/null
     while [ $tmp_num -lt $srd_num ]; do
         if [ $((srd_num - tmp_num)) -gt $srd_max_per_turn ]; then
@@ -92,24 +91,22 @@ trap '_clean' EXIT
 
 . $scriptdir/utils.sh
 
-data_arry=($(ls $datadir))
 srd_paths=$(get_config ".functionality|.srd_paths")
 srd_limit=$(get_config '.functionality|.srd_limit')
 file_limit=$(get_config '.functionality|.file_limit')
 
 ### Seal file upper limit
 _test_add_file $file_limit
-sidx=$((RANDOM % ${#data_arry[@]}))
-_seal $datadir/${data_arry[$sidx]} $testfiledir
+_seal 2>/dev/null
 if [ $? -eq 0 ]; then
     verbose ERROR "test file upper limit failed!"
     exit 1
 fi
 
 ### Srd upper limit
-#_srd "$srd_paths" "$srd_limit"
-#srd 32
-#if [ $? -eq 0 ]; then
-#    verbose ERROR "test srd upper limit failed!"
-#    exit 1
-#fi
+_srd "$srd_paths" "$srd_limit"
+set_srd 32
+if [ $? -eq 0 ]; then
+    verbose ERROR "test srd upper limit failed!"
+    exit 1
+fi
