Fix tbb concurrent bug

diff --git a/test/integration/functionality/500_upgrade b/test/integration/functionality/500_upgrade
--- a/test/integration/functionality/500_upgrade
+++ b/test/integration/functionality/500_upgrade
@@ -5,6 +5,46 @@ function kill_current()
     wait $newsworkerpid &>/dev/null
 }
 
+function srd_backend()
+{
+    # Get current available max per turn
+    local srd_paths=$(get_config ".functionality|.srd_paths")
+    local srd_max_per_turn=$(get_config ".functionality|.srd_max_per_turn")
+    local real_max_per_turn=0
+    local srd_paths_test=($(echo $srd_paths | sed -e 's/,/ /g' -e 's/\[\|\]//g' -e 's/\"//g'))
+    local tmp=""
+    for path in ${srd_paths_test[@]}; do
+        if [ ! -d $path ]; then
+            mkdir -p $path
+        fi
+        tmp=$(df -h $path | tail -n 1 | awk '{print $4}')
+        tmp=${tmp%[a-zA-Z]*}
+        ((real_max_per_turn += tmp))
+    done
+    if [ $srd_max_per_turn -gt $real_max_per_turn ]; then
+        srd_max_per_turn=$real_max_per_turn
+    fi
+
+    # Srd task
+    local srd_num=200000
+    local tmp_num=0
+    local cur_turn=0
+    srd_disk_change "$srd_paths" "add" &>/dev/null
+    while [ $tmp_num -lt $srd_num ]; do
+        if [ $((srd_num - tmp_num)) -gt $srd_max_per_turn ]; then
+            cur_turn=$srd_max_per_turn
+        else
+            cur_turn=$((srd_num - tmp_num))
+        fi
+        srd $cur_turn &>/dev/null
+        if [ $? -ne 0 ]; then
+            verbose ERROR "srd failed!" n
+            exit 1
+        fi
+        ((tmp_num+=cur_turn))
+    done
+}
+
 ########## MAIN BODY ##########
 # basic variable
 basedir=$(cd `dirname $0`;pwd)
@@ -19,6 +59,8 @@ trap 'kill_current' INT
 
 
 cd $testdir
+srd_backend &
+sleep 10
 ./bin/crust-sworker -c etc/Config.json --offline --debug --upgrade &>${sworkerlog}2 &
 newsworkerpid=$!
 oldsworkerpid=$(cat $sworkerpidfile)
